
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Set your Atlas connection string here or via Render dashboard
      - MONGODB_URL=your-mongodb-atlas-connection-string
    volumes:
      - ./:/app
